<?php

namespace HeavenTNBundle\Repository;

/**
 * LignedecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignedecommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdProduct($idProduct)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM HeavenTNBundle:Commandes m WHERE m.idProduct='$idProduct'");
        return $query->getResult();
    }
}
